### ISSUE TITLE
Highlighting on Qutebrowser

### ISSUE THREAD

**Issue by wgmayer0** [Andreto/Custom-Highlight#8]
Hello,

I use Qutebrowser which uses Chromium as a backend to browse the web.

I posted this question and based on the answer from the developer, I wanted to know if anyone here would know the answer to my question:

https://github.com/qutebrowser/qutebrowser/discussions/5978

Thanks!

**Comment by Andreto** [comment]
This extension uses the css `::selection` keyword to change the highlight color.
If you are going to use it in a stylesheet you could probably do something like this:
``` css
::selection {
  color: #161B22;
  background-color: #005BFF;
}
```
You might have to use !important to override page defaults, but for most stylesheet injectors this is not necessary since the new style is applied at a later point. You will have to try and see.
``` css
::selection {
  color: #161B22 !important;
  background-color: #005BFF !important;
}
```
